### ISSUE TITLE
Segmentation Fault when running a url

### ISSUE THREAD

**Issue by danweller18** [buffer/thug#175] opened 2016-06-29 21:21 UTC
Running a url query to `sunlait.com` and I get this over and over again

<pre>[2016-06-29 17:08:38] Unknown ActiveX Object (WScript.Shell) attribute: $family
[2016-06-29 17:08:38] Unknown ActiveX Object (WScript.Shell) attribute: nodeName
[2016-06-29 17:08:38] Unknown ActiveX Object (WScript.Shell) attribute: length
[2016-06-29 17:08:38] Unknown ActiveX Object (WScript.Shell) attribute: __members__
[2016-06-29 17:08:38] Unknown ActiveX Object (WScript.Shell) attribute: __methods__</pre>

Finally the last grouping I see is:

<pre>[2016-06-29 17:08:38] Unknown ActiveX Object (WScript.Shell) attribute: $family
[2016-06-29 17:08:38] Unknown ActiveX Object (WScript.Shell) attribute: nodeName
[2016-06-29 17:08:38] Unknown ActiveX Object (WScript.Shell) attribute: length
[2016-06-29 17:08:38] Unknown ActiveX Object (WScript.Shell) attribute: __members__
[2016-06-29 17:08:38] Unknown ActiveX Object (WScript.Shell) attribute: __methods__
Segmentation fault (core dumped)</pre>

I can post the shell output but it is very very long. Any ideas why this might be happening? Note, it works for every other url I have tried.

**Comment by buffer** [comment] 2016-06-30 07:29
I will take a look at it as soon as possible. I suspect this bug to be related with libemu. I have observed a similar behavior due to a detected heap corruption but just on a Ubuntu VM. Could you confirm the environment is the same for you? Thanks.

**Comment by buffer** [comment] 2016-06-30 09:25
The issue seems to be related to V8/PyV8. Let me investigate and hopefully find a solution for that. Thanks!

**Comment by buffer** [comment] 2016-12-09 10:22
I performed some tests with the latest version of Thug and it seems like the issue is not reproducible anymore. Closing the issue.

**Closed by buffer** 2016-12-09 10:22 UTC
Labels: bug
