### ISSUE TITLE
new version - missing graph.svg

### ISSUE THREAD

**Issue by arunkhan1984** [buffer/thug#173] opened 2016-06-20 16:13 UTC
Using thug via docker installation, very good tool. 
Recently installed the new version but it seems the graph.svg file is not being created within the analysis folder.

Is this feature removed completely or can it be enabled?

Thanks

**Comment by buffer** [comment] 2016-06-21 08:37
The feature has not disappeared. Just enable the file logging mode (-F) and the JSON logging mode (-Z) and the SVG file will be generated in the analysis directory.

**Comment by arunkhan1984** [comment] 2016-06-22 14:11
Hi Buffer,

Thanks for the message. I ran the command with -FZ but still nothing. I am using the docker io within remnux. Do you think may be an issue with remnux? See below the file tree for the results I got for running thug on google main page:
.:
total 20
drwxr-xr-x 5 vboxadd vboxsf 4096 Jun 22 10:01 .
drwxr-xr-x 5 vboxadd vboxsf 4096 Jun 22 10:00 ..
drwxr-xr-x 4 vboxadd vboxsf 4096 Jun 22 10:01 analysis
drwxr-xr-x 3 vboxadd vboxsf 4096 Jun 22 10:01 image
drwxr-xr-x 3 vboxadd vboxsf 4096 Jun 22 10:01 text

./analysis:
total 16
drwxr-xr-x 4 vboxadd vboxsf 4096 Jun 22 10:01 .
drwxr-xr-x 5 vboxadd vboxsf 4096 Jun 22 10:01 ..
drwxr-xr-x 2 vboxadd vboxsf 4096 Jun 22 10:01 json
drwxr-xr-x 2 vboxadd vboxsf 4096 Jun 22 10:01 maec11

./analysis/json:
total 52
drwxr-xr-x 2 vboxadd vboxsf  4096 Jun 22 10:01 .
drwxr-xr-x 4 vboxadd vboxsf  4096 Jun 22 10:01 ..
-rw-r--r-- 1 vboxadd vboxsf 42759 Jun 22 10:01 analysis.json

./analysis/maec11:
total 36
drwxr-xr-x 2 vboxadd vboxsf  4096 Jun 22 10:01 .
drwxr-xr-x 4 vboxadd vboxsf  4096 Jun 22 10:01 ..
-rw-r--r-- 1 vboxadd vboxsf 26076 Jun 22 10:01 analysis.xml

./image:
total 12
drwxr-xr-x 3 vboxadd vboxsf 4096 Jun 22 10:01 .
drwxr-xr-x 5 vboxadd vboxsf 4096 Jun 22 10:01 ..
drwxr-xr-x 2 vboxadd vboxsf 4096 Jun 22 10:01 x-icon

./image/x-icon:
total 16
drwxr-xr-x 2 vboxadd vboxsf 4096 Jun 22 10:01 .
drwxr-xr-x 3 vboxadd vboxsf 4096 Jun 22 10:01 ..
-rw-r--r-- 1 vboxadd vboxsf 5430 Jun 22 10:01 f3418a443e7d841097c714d69ec4bcb8

./text:
total 12
drwxr-xr-x 3 vboxadd vboxsf 4096 Jun 22 10:01 .
drwxr-xr-x 5 vboxadd vboxsf 4096 Jun 22 10:01 ..
drwxr-xr-x 2 vboxadd vboxsf 4096 Jun 22 10:01 html; charset=UTF-8

./text/html; charset=UTF-8:
total 32
drwxr-xr-x 2 vboxadd vboxsf  4096 Jun 22 10:01 .
drwxr-xr-x 3 vboxadd vboxsf  4096 Jun 22 10:01 ..
-rw-r--r-- 1 vboxadd vboxsf 22695 Jun 22 10:01 f3c779f4674ef018933dad025de9a06e

**Comment by buffer** [comment] 2016-06-23 08:21
Could you please try upgrading REMnux and give it a try again? I know that a dependency (pygraphviz) was missing in one of the last releases of remnux-thug and this could explain the issue. The issue is fixed now and I can not reproduce it on an (updated) REMnux VM.

**Comment by arunkhan1984** [comment] 2016-06-23 13:34
I installed a new remnux distro (from their website) and ran all updates on remnux. Then installed docker.io and then ran thug. I had no errors on installation and I was able to use thug but again no graph.svg created.

Thanks

**Comment by buffer** [comment] 2016-06-23 16:48
Can you please install explicitely pygraphviz using apt-get and try again? I could be wrong but the package name should be python-pygraphviz

**Comment by arunkhan1984** [comment] 2016-06-23 17:10
its stating it is already at the newest version.

Command used: sudo apt-get install python-pygraphviz

**Comment by buffer** [comment] 2016-06-24 08:35
That's really strange. Just a last attempt. Please try moving in the src directory and run 

pip install -r requirements.txt

By the way probably the best thing to do would be to contact Lenny @ REMnux.

**Comment by arunkhan1984** [comment] 2016-07-05 12:00
Hi Buffer
Unfortunately Lenny has not got back to me about this.
I used another thug repository (honeynet/thug) on the newest remnux and that has brought back the graph svg file again.

The thug repository seems to be on 0.6.7 not 0.7.1.

Can I ask how you are installing your thug repository (0.7.1) onto REMnux.

I used the command:

sudo docker pull remnux/thug

Thanks

**Comment by buffer** [comment] 2016-07-05 14:53
Lenny, thanks for the support! Really appreciated.

**Comment by arunkhan1984** [comment] 2016-07-05 14:59
Hi Lenny,

Thank you that has worked and I have seen the graph svg file.

Thanks both

**Comment by lennyzeltser** [comment] 2016-07-05 22:21
I address the problem in the "remnux/thug" Docker image of Thug, so that now it is able to generate SVG files.

**Comment by buffer** [comment] 2016-07-06 08:26
Thanks Lenny!

**Closed by buffer** 2016-07-06 08:26 UTC
Labels: configuration
